### ISSUE TITLE
Cake.Fastlane.Pilot not working

### ISSUE THREAD

**Issue by donnib** [RLittlesII/Cake.Fastlane#14]
Hi,
I found your repo and tried Fastlane.Deliver which worked fine but Fastlane.Pilot is not. I get :

```
Please ensure to use one of the available commands (help, upload, distribute, builds, add, list, find, remove, export, import)
```
and it seems it's because fastlane is not provided the action such as ```upload``` in this case, is there something additional i need to do or it's missing from the implementation ?

Also i get following : 
```
14:58:27]: fastlane detected a Gemfile in the current directory
[14:58:27]: however it seems like you don't use `bundle exec`
```

**Comment by donnib** [comment]
@RLittlesII i will provide that tomorrow but it's very basic, i am just trying to upload an ipa and from the code it's very obvious it fails because as far as i can see the upload argument is never given to fastlane pilot so as soon as i write fastlane pilot update then it works.

**Comment by RLittlesII** [comment]
@donnib Yes, you are correct.  I noticed that looking at the docs that pilot works different than some of the other commands.  I am marking this as a bug and will attempt to get this addressed quickly.  

And I understand it is basic.  It is still helpful to know the versions of the tools.  It could be I just whiffed on the implementation, or that pilot changed and I am not up to date (which is not the case here).

**Comment by RLittlesII** [comment]
@donnib Can you verify if [package 0.4.1-build-cake-versi0001](https://www.myget.org/feed/cake-fastlane/package/nuget/Cake.Fastlane/0.4.1-build-cake-versi0001) resolves this issue?  I added a `PilotCommand` to the configuration and it defaults to `upload`.

**Comment by donnib** [comment]
@RLittlesII That did the trick yes. Thank you for your quick response. Regarding the version i use. I use latest which at the moment is : `2.105.0`

**Comment by RLittlesII** [comment]
@donnib Glad that worked.  I'll release a 0.4.1 version shortly and push to NuGet.  Thanks for identifying this, and thank you for your help getting this resolved.  Apologies for any inconvenience.
