### ISSUE TITLE
fastlane: Be able to update fastlane through Cake

### ISSUE THREAD

**Issue by donnib** [RLittlesII/Cake.Fastlane#16]
Hi,
I think it would be nice to be able to upgrade Fastlane through the Cake script so some api would be nice for this. 

If you don't upgrade you typically would get something like this : 
```
#######################################################################
# fastlane 2.105.0 is available. You are on 2.104.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
```

/donnib

**Comment by RLittlesII** [comment]
@donnib Normally, I prefer to allow a package manager to handle updates of my dependencies in my scripts.  That said, fastlane provides it's own built in update mechanism and it shouldn't be a huge hassle to implement.
